//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Utilities {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailsResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Utilities.DetailsResources", typeof(DetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration.
        /// </summary>
        internal static string AnimalDurationTitle {
            get {
                return ResourceManager.GetString("AnimalDurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animal Lenght.
        /// </summary>
        internal static string AnimalLenghtTitle {
            get {
                return ResourceManager.GetString("AnimalLenghtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lifespan.
        /// </summary>
        internal static string AnimalLifespanTitle {
            get {
                return ResourceManager.GetString("AnimalLifespanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animal Weight.
        /// </summary>
        internal static string AnimalWeightTitle {
            get {
                return ResourceManager.GetString("AnimalWeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Date.
        /// </summary>
        internal static string DisplayDateTitle {
            get {
                return ResourceManager.GetString("DisplayDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diurnal.
        /// </summary>
        internal static string DiurnalDurationValue {
            get {
                return ResourceManager.GetString("DiurnalDurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully loaded cards: {0}.
        /// </summary>
        internal static string DownloadingFinishContent {
            get {
                return ResourceManager.GetString("DownloadingFinishContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed.
        /// </summary>
        internal static string DownloadingFinishTitle {
            get {
                return ResourceManager.GetString("DownloadingFinishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Executing {0}/{1} services;.
        /// </summary>
        internal static string DownloadingProgressContent {
            get {
                return ResourceManager.GetString("DownloadingProgressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received {0} cards.
        /// </summary>
        internal static string DownloadingProgressContentPostfix {
            get {
                return ResourceManager.GetString("DownloadingProgressContentPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading....
        /// </summary>
        internal static string DownloadingProgressTitle {
            get {
                return ResourceManager.GetString("DownloadingProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nocturnal.
        /// </summary>
        internal static string NocturnalDurationValue {
            get {
                return ResourceManager.GetString("NocturnalDurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Origin Place.
        /// </summary>
        internal static string OriginPlaceTitle {
            get {
                return ResourceManager.GetString("OriginPlaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Age.
        /// </summary>
        internal static string SelfAgeTitle {
            get {
                return ResourceManager.GetString("SelfAgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is me!.
        /// </summary>
        internal static string SelfDetailsTitle {
            get {
                return ResourceManager.GetString("SelfDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorite Author.
        /// </summary>
        internal static string SelfFavoriteAuthorTitle {
            get {
                return ResourceManager.GetString("SelfFavoriteAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Want working.
        /// </summary>
        internal static string SelfWantWorkTitle {
            get {
                return ResourceManager.GetString("SelfWantWorkTitle", resourceCulture);
            }
        }
    }
}
